# Generated by Django 4.1.5 on 2023-03-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_customuser_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=150)),
                ("address", models.TextField(help_text="street 11, block 4")),
                (
                    "postal_code",
                    models.TextField(help_text="312342131232", max_length=20),
                ),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
            ],
        ),
    ]
